### ISSUE TITLE
RGB Fallback

### ISSUE THREAD

**Issue by anthonyshort** [anthonyshort/stitch-css#1]
Need an RGB fallback mixin that leverages Sass's colour function.

  #id {
    @include rgb(property, #color);
  }

  #id {
     background: #color;
     background: rgb(0,0,0);
  }

**Comment by chrisbuttery** [comment]
Something like :

@mixin rgba($property, $color, $alpha:false){
    #{$property}: $color;

```
@if ($alpha){
    #{$property}: rgba($color, $alpha);
}
@else {
    #{$property}: rgba($color, 1);
}
```

}

$black : #000;
$red: #ff0000;

@include rgba(color, $red, 0.8);
// @include rgba(color, $red);
// @include rgba(color, #ff0000, 0.8);
// @include rgba(color, #ff0000);

**Comment by chrisbuttery** [comment]
Closing this as it has recently been added to pre-release
