### ISSUE TITLE
Use :focus styles from Normalize.css

### ISSUE THREAD

**Issue by necolas** [anthonyshort/stitch-css#13]
I see that your reset is largely based on normalize.css but you're killing off all `:focus` styles by default, which is going to introduce accessibility problems, especially for keyboard users.

You should include something like the normalize.css `:focus` style normalization if you want to do away with the webkit focus ring. Just apply it to focus states on form elements too.

And your print styles look to be largely from HTML5 Boilerplate, so you might want to update them to harvest some of the latest updates from that project.

**Comment by peschee** [comment]
@necolas Care to make a PR?
