### ISSUE TITLE
Typo in the stitchcss website for the 'force-scrollbars' mixin.

### ISSUE THREAD

**Issue by jannisg** [anthonyshort/stitch-css#14]
Heya,
just noticed a little discrepancy between the actual `mixin` name and what the [documentation](http://stitchcss.com/#force_scrollbar) shows.

The documentation shows the mixin to be `force-scrollbar` whereas the files seem to be in plural, `force-scrollbars`.

Small but noticeable difference since it throws an error if used incorrectly.

Cheers,
J.

**Comment by chrisbuttery** [comment]
Thanks for spotting this, the correction has been made: http://stitchcss.com/#force_scrollbars
