### ISSUE TITLE
The prefix mixin clashes with Susy grids

### ISSUE THREAD

**Issue by lmartins** [anthonyshort/stitch-css#28]
Hi, 

Not really a bug but still a problem, Susy compass grids also have a "prefix" mixin, making it impossible to use both libraries in the same project.

Is this something you would be able to change?

Regards.

**Comment by anthonyshort** [comment]
This is where we really need some sort of name spacing or module system for mixins. I put together a gist the other day that was actually addressing this problem. The only real solution at the moment is for libraries to prefix their mixin names to avoid conflicts. Which is a pain as different libraries may have their own grid mixins and so on. 

I would like to update stitch and add prefixed mixin names at some point. It's useful for maintaining style sheets too so you know where the mixins came from. 

Any suggestions?

**Comment by lmartins** [comment]
Hi Anthony,

I saw your post, and in my mind it really makes sense, even more with so many amazing tools for Sass emerging. Im affraid im not skilled enough to give a valid suggestion here. For now im using Stitch mixins manually and it probably will work just fine for what i need. But again, your case for namespacing in Sass sounded just about right.

Thanks Anthony.

**Comment by anthonyshort** [comment]
You can import the Stitch files individually if you don't want the prefix mixin. That mixin is only used for the CSS3 stuff so you could leave that out and just import what you need. 

``` scss
@import 'stitch/patterns/layout';
@import 'stitch/patterns/forms';
```

or even just

``` scss
@import 'stitch/patterns';
```

Which won't include the prefix mixin but will include all of the patterns.

Any of the files [in this directory](https://github.com/anthonyshort/stitch-css/tree/master/stylesheets/stitch/patterns) will include that section.
