### ISSUE TITLE
Adding inline icons

### ISSUE THREAD

**Issue by anthonyshort** [anthonyshort/stitch-css#8]
Mixin for adding inline icons next to text. Usually added to a span or an anchor.

**Comment by chrisbuttery** [comment]
Are you thinking 

`<a href="">add a background image of an icon to me</a>`

or 

``````
<a href="">
    <img src="some-sweet-icon.png"'>
    Hows this sweet icon
</a>```
``````

**Comment by chrisbuttery** [comment]
Closing this as this mixin has recently been added to pre-release
